// Generated by scripts/build-ui-types.mjs from the actual shared UI. Do not hand edit.
declare module "@taskasaur/ui/primitives/select" {
import * as React from "react";
import { Select as SelectPrimitive } from "@base-ui/react/select";
const Select: typeof SelectPrimitive.Root;
function SelectGroup({ className, ...props }: SelectPrimitive.Group.Props): import("react/jsx-runtime").JSX.Element;
function SelectValue({ className, ...props }: SelectPrimitive.Value.Props): import("react/jsx-runtime").JSX.Element;
function SelectTrigger({ className, size, children, ...props }: SelectPrimitive.Trigger.Props & {
    size?: "sm" | "default";
}): import("react/jsx-runtime").JSX.Element;
function SelectContent({ className, children, side, sideOffset, align, alignOffset, alignItemWithTrigger, ...props }: SelectPrimitive.Popup.Props & Pick<SelectPrimitive.Positioner.Props, "align" | "alignOffset" | "side" | "sideOffset" | "alignItemWithTrigger">): import("react/jsx-runtime").JSX.Element;
function SelectLabel({ className, ...props }: SelectPrimitive.GroupLabel.Props): import("react/jsx-runtime").JSX.Element;
function SelectItem({ className, children, ...props }: SelectPrimitive.Item.Props): import("react/jsx-runtime").JSX.Element;
function SelectSeparator({ className, ...props }: SelectPrimitive.Separator.Props): import("react/jsx-runtime").JSX.Element;
function SelectScrollUpButton({ className, ...props }: React.ComponentProps<typeof SelectPrimitive.ScrollUpArrow>): import("react/jsx-runtime").JSX.Element;
function SelectScrollDownButton({ className, ...props }: React.ComponentProps<typeof SelectPrimitive.ScrollDownArrow>): import("react/jsx-runtime").JSX.Element;
export { Select, SelectContent, SelectGroup, SelectItem, SelectLabel, SelectScrollDownButton, SelectScrollUpButton, SelectSeparator, SelectTrigger, SelectValue, };

}
declare module "@taskasaur/ui/choice-select" {
import * as React from "react";
import { SelectTrigger } from "@taskasaur/ui/primitives/select";
export interface Choice {
    value: string;
    label: React.ReactNode;
    disabled?: boolean;
    group?: string;
}
/** Application composition of the unmodified official shadcn Select. */
export function ChoiceSelect({ options, value, onValueChange, placeholder, className, ...props }: {
    options: Choice[];
    value?: string;
    onValueChange: (value: string) => void;
    placeholder?: string;
} & Omit<React.ComponentProps<typeof SelectTrigger>, "value" | "onChange">): import("react/jsx-runtime").JSX.Element;
/** v1 HTML-select compatibility; new plugins use ChoiceSelect/Select directly. */
export function LegacySelect({ children, value, defaultValue, onChange, multiple, className, ...props }: React.SelectHTMLAttributes<HTMLSelectElement>): import("react/jsx-runtime").JSX.Element;

}
declare module "@taskasaur/ui/primitives/input" {
import * as React from "react";
function Input({ className, type, ...props }: React.ComponentProps<"input">): import("react/jsx-runtime").JSX.Element;
export { Input };

}
declare module "@taskasaur/ui/primitives/textarea" {
import * as React from "react";
function Textarea({ className, ...props }: React.ComponentProps<"textarea">): import("react/jsx-runtime").JSX.Element;
export { Textarea };

}
declare module "@taskasaur/ui/primitives/checkbox" {
import { Checkbox as CheckboxPrimitive } from "@base-ui/react/checkbox";
function Checkbox({ className, ...props }: CheckboxPrimitive.Root.Props): import("react/jsx-runtime").JSX.Element;
export { Checkbox };

}
declare module "@taskasaur/ui/primitives/button" {
import { Button as ButtonPrimitive } from "@base-ui/react/button";
import { type VariantProps } from "class-variance-authority";
const buttonVariants: (props?: ({
    variant?: "link" | "default" | "outline" | "secondary" | "ghost" | "destructive" | null | undefined;
    size?: "sm" | "default" | "xs" | "lg" | "icon" | "icon-xs" | "icon-sm" | "icon-lg" | null | undefined;
} & import("class-variance-authority/types").ClassProp) | undefined) => string;
function Button({ className, variant, size, ...props }: ButtonPrimitive.Props & VariantProps<typeof buttonVariants>): import("react/jsx-runtime").JSX.Element;
export { Button, buttonVariants };

}
declare module "@taskasaur/ui/primitives/label" {
import * as React from "react";
function Label({ className, ...props }: React.ComponentProps<"label">): import("react/jsx-runtime").JSX.Element;
export { Label };

}
declare module "@taskasaur/ui/primitives/switch" {
import { Switch as SwitchPrimitive } from "@base-ui/react/switch";
function Switch({ className, size, ...props }: SwitchPrimitive.Root.Props & {
    size?: "sm" | "default";
}): import("react/jsx-runtime").JSX.Element;
export { Switch };

}
declare module "@taskasaur/ui/fields" {
import { type Field, type Value, type RecordSchema } from "@taskasaur/platform/field-types";
export const ReferenceOptionsContext: import("react").Context<Record<string, {
    id: string;
    label: string;
}[]>>;
export function FieldInput({ definition: f, value, onChange, disabled, }: {
    definition: Field;
    value: Value | undefined;
    onChange: (value: Value) => void;
    disabled?: boolean;
}): import("react/jsx-runtime").JSX.Element;
export function displayValue(value: Value | undefined, f?: Field): string;
export function RecordForm({ schema, initial, onSave, onCancel, }: {
    schema: RecordSchema;
    initial?: Record<string, Value>;
    onSave: (data: Record<string, Value>) => Promise<void>;
    onCancel: () => void;
}): import("react/jsx-runtime").JSX.Element;

}
declare module "@taskasaur/ui/primitives/popover" {
import * as React from "react";
import { Popover as PopoverPrimitive } from "@base-ui/react/popover";
function Popover({ ...props }: PopoverPrimitive.Root.Props): import("react/jsx-runtime").JSX.Element;
function PopoverTrigger({ ...props }: PopoverPrimitive.Trigger.Props): import("react/jsx-runtime").JSX.Element;
function PopoverContent({ className, align, alignOffset, side, sideOffset, ...props }: PopoverPrimitive.Popup.Props & Pick<PopoverPrimitive.Positioner.Props, "align" | "alignOffset" | "side" | "sideOffset">): import("react/jsx-runtime").JSX.Element;
function PopoverHeader({ className, ...props }: React.ComponentProps<"div">): import("react/jsx-runtime").JSX.Element;
function PopoverTitle({ className, ...props }: PopoverPrimitive.Title.Props): import("react/jsx-runtime").JSX.Element;
function PopoverDescription({ className, ...props }: PopoverPrimitive.Description.Props): import("react/jsx-runtime").JSX.Element;
export { Popover, PopoverContent, PopoverDescription, PopoverHeader, PopoverTitle, PopoverTrigger, };

}
declare module "@taskasaur/ui/primitives/dropdown-menu" {
import * as React from "react";
import { Menu as MenuPrimitive } from "@base-ui/react/menu";
function DropdownMenu({ ...props }: MenuPrimitive.Root.Props): import("react/jsx-runtime").JSX.Element;
function DropdownMenuPortal({ ...props }: MenuPrimitive.Portal.Props): import("react/jsx-runtime").JSX.Element;
function DropdownMenuTrigger({ ...props }: MenuPrimitive.Trigger.Props): import("react/jsx-runtime").JSX.Element;
function DropdownMenuContent({ align, alignOffset, side, sideOffset, className, ...props }: MenuPrimitive.Popup.Props & Pick<MenuPrimitive.Positioner.Props, "align" | "alignOffset" | "side" | "sideOffset">): import("react/jsx-runtime").JSX.Element;
function DropdownMenuGroup({ ...props }: MenuPrimitive.Group.Props): import("react/jsx-runtime").JSX.Element;
function DropdownMenuLabel({ className, inset, ...props }: MenuPrimitive.GroupLabel.Props & {
    inset?: boolean;
}): import("react/jsx-runtime").JSX.Element;
function DropdownMenuItem({ className, inset, variant, ...props }: MenuPrimitive.Item.Props & {
    inset?: boolean;
    variant?: "default" | "destructive";
}): import("react/jsx-runtime").JSX.Element;
function DropdownMenuSub({ ...props }: MenuPrimitive.SubmenuRoot.Props): import("react/jsx-runtime").JSX.Element;
function DropdownMenuSubTrigger({ className, inset, children, ...props }: MenuPrimitive.SubmenuTrigger.Props & {
    inset?: boolean;
}): import("react/jsx-runtime").JSX.Element;
function DropdownMenuSubContent({ align, alignOffset, side, sideOffset, className, ...props }: React.ComponentProps<typeof DropdownMenuContent>): import("react/jsx-runtime").JSX.Element;
function DropdownMenuCheckboxItem({ className, children, checked, inset, ...props }: MenuPrimitive.CheckboxItem.Props & {
    inset?: boolean;
}): import("react/jsx-runtime").JSX.Element;
function DropdownMenuRadioGroup({ ...props }: MenuPrimitive.RadioGroup.Props): import("react/jsx-runtime").JSX.Element;
function DropdownMenuRadioItem({ className, children, inset, ...props }: MenuPrimitive.RadioItem.Props & {
    inset?: boolean;
}): import("react/jsx-runtime").JSX.Element;
function DropdownMenuSeparator({ className, ...props }: MenuPrimitive.Separator.Props): import("react/jsx-runtime").JSX.Element;
function DropdownMenuShortcut({ className, ...props }: React.ComponentProps<"span">): import("react/jsx-runtime").JSX.Element;
export { DropdownMenu, DropdownMenuPortal, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuGroup, DropdownMenuLabel, DropdownMenuItem, DropdownMenuCheckboxItem, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator, DropdownMenuShortcut, DropdownMenuSub, DropdownMenuSubTrigger, DropdownMenuSubContent, };

}
declare module "@taskasaur/ui/collection-view-model" {
import { type Field, type Query, type Value, type RecordSchema } from "@taskasaur/platform/field-types";
import type { ResourceRecord } from "@taskasaur/platform/plugin-sdk";
export const viewModes: readonly ["short-table", "long-table", "board", "short-table-folder", "long-table-folder", "board-folder"];
export type ViewMode = (typeof viewModes)[number];
export const viewLabels: Record<ViewMode, string>;
export interface Grouping {
    id: string;
    field: string;
    enabled: boolean;
}
export interface GroupSegment {
    field: string;
    key: string;
}
export interface CollectionViewState {
    version: 2;
    query: Query;
    columns: string[];
    /** Full field order, including hidden columns; older callers may omit it. */
    columnOrder?: string[];
    groups: Grouping[];
    mode: ViewMode;
    path: GroupSegment[];
    collapsed: string[];
}
export interface GroupNode {
    id: string;
    field: Field;
    value: Value;
    path: GroupSegment[];
    rows: ResourceRecord[];
    children: GroupNode[];
}
/** Keep hidden fields in the same order so toggling visibility never moves them. */
export function resolveColumnOrder(fields: Field[], preferred?: string[]): string[];
/** Display preferences are local; search from older table preferences is deliberately retired. */
export function normalizeView(saved: Partial<CollectionViewState> | undefined, schema: RecordSchema): CollectionViewState;
export function moveRule<T>(rules: T[], index: number, direction: -1 | 1): T[];
export function groupKey(field: Field, value: Value | undefined): string;
export function activeGroups(groups: Grouping[], fields: Field[]): Field[];
export function groupRecords(rows: ResourceRecord[], fields: Field[], depth?: number, parent?: GroupSegment[]): GroupNode[];
/** Resolve the longest valid prefix after changes to grouping, filters or data. */
export function resolveGroupPath(tree: GroupNode[], path: GroupSegment[]): {
    ancestors: GroupNode[];
    children: GroupNode[];
};

}
declare module "@taskasaur/ui/query-controls" {
import type { Field, Query } from "@taskasaur/platform/field-types";
import { type Grouping, type ViewMode } from "@taskasaur/ui/collection-view-model";
export function OrderButtons({ index, count, kind, onMove, }: {
    index: number;
    count: number;
    kind: string;
    onMove: (direction: -1 | 1) => void;
}): import("react/jsx-runtime").JSX.Element;
export function QueryControls({ fields, query, onChange, columns, columnOrder, onColumns, groups, onGroups, mode, onMode, }: {
    fields: Field[];
    query: Query;
    onChange: (query: Query) => void;
    columns: string[];
    columnOrder?: string[];
    onColumns: (columns: string[], order?: string[]) => void;
    groups: Grouping[];
    onGroups: (groups: Grouping[]) => void;
    mode: ViewMode;
    onMode: (mode: ViewMode) => void;
}): import("react/jsx-runtime").JSX.Element;

}
declare module "@taskasaur/ui/primitives/table" {
import * as React from "react";
function Table({ className, ...props }: React.ComponentProps<"table">): import("react/jsx-runtime").JSX.Element;
function TableHeader({ className, ...props }: React.ComponentProps<"thead">): import("react/jsx-runtime").JSX.Element;
function TableBody({ className, ...props }: React.ComponentProps<"tbody">): import("react/jsx-runtime").JSX.Element;
function TableFooter({ className, ...props }: React.ComponentProps<"tfoot">): import("react/jsx-runtime").JSX.Element;
function TableRow({ className, ...props }: React.ComponentProps<"tr">): import("react/jsx-runtime").JSX.Element;
function TableHead({ className, ...props }: React.ComponentProps<"th">): import("react/jsx-runtime").JSX.Element;
function TableCell({ className, ...props }: React.ComponentProps<"td">): import("react/jsx-runtime").JSX.Element;
function TableCaption({ className, ...props }: React.ComponentProps<"caption">): import("react/jsx-runtime").JSX.Element;
export { Table, TableHeader, TableBody, TableFooter, TableHead, TableRow, TableCell, TableCaption, };

}
declare module "@taskasaur/ui/primitives/breadcrumb" {
import * as React from "react";
import { useRender } from "@base-ui/react/use-render";
function Breadcrumb({ className, ...props }: React.ComponentProps<"nav">): import("react/jsx-runtime").JSX.Element;
function BreadcrumbList({ className, ...props }: React.ComponentProps<"ol">): import("react/jsx-runtime").JSX.Element;
function BreadcrumbItem({ className, ...props }: React.ComponentProps<"li">): import("react/jsx-runtime").JSX.Element;
function BreadcrumbLink({ className, render, ...props }: useRender.ComponentProps<"a">): React.ReactElement<unknown, string | React.JSXElementConstructor<any>>;
function BreadcrumbPage({ className, ...props }: React.ComponentProps<"span">): import("react/jsx-runtime").JSX.Element;
function BreadcrumbSeparator({ children, className, ...props }: React.ComponentProps<"li">): import("react/jsx-runtime").JSX.Element;
function BreadcrumbEllipsis({ className, ...props }: React.ComponentProps<"span">): import("react/jsx-runtime").JSX.Element;
export { Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink, BreadcrumbPage, BreadcrumbSeparator, BreadcrumbEllipsis, };

}
declare module "@taskasaur/ui/primitives/card" {
import * as React from "react";
function Card({ className, size, ...props }: React.ComponentProps<"div"> & {
    size?: "default" | "sm";
}): import("react/jsx-runtime").JSX.Element;
function CardHeader({ className, ...props }: React.ComponentProps<"div">): import("react/jsx-runtime").JSX.Element;
function CardTitle({ className, ...props }: React.ComponentProps<"div">): import("react/jsx-runtime").JSX.Element;
function CardDescription({ className, ...props }: React.ComponentProps<"div">): import("react/jsx-runtime").JSX.Element;
function CardAction({ className, ...props }: React.ComponentProps<"div">): import("react/jsx-runtime").JSX.Element;
function CardContent({ className, ...props }: React.ComponentProps<"div">): import("react/jsx-runtime").JSX.Element;
function CardFooter({ className, ...props }: React.ComponentProps<"div">): import("react/jsx-runtime").JSX.Element;
export { Card, CardHeader, CardFooter, CardTitle, CardAction, CardDescription, CardContent, };

}
declare module "@taskasaur/ui/collection-view" {
import { type ReactNode } from "react";
import type { Field, RecordSchema, Value } from "@taskasaur/platform/field-types";
import type { ResourceRecord } from "@taskasaur/platform/plugin-sdk";
import { type CollectionViewState } from "@taskasaur/ui/collection-view-model";
export interface CellContext {
    row: ResourceRecord;
    field: Field;
    value: Value | undefined;
    defaultContent: ReactNode;
    writable: boolean;
    update: (patch: Record<string, Value>) => Promise<void>;
}
export interface ColumnOptions {
    header?: ReactNode;
    className?: string;
    width?: number | string;
}
export interface CollectionViewProps {
    schema: RecordSchema;
    rows: ResourceRecord[];
    state: CollectionViewState;
    onChange: (patch: Partial<CollectionViewState>) => void;
    onOpen?: (row: ResourceRecord) => void;
    renderActions?: (row: ResourceRecord) => ReactNode;
    renderCell?: (context: CellContext) => ReactNode;
    renderCard?: (row: ResourceRecord, defaultContent: ReactNode) => ReactNode;
    columnOptions?: Record<string, ColumnOptions>;
    writable?: (row: ResourceRecord) => boolean;
    onUpdate?: (row: ResourceRecord, patch: Record<string, Value>) => Promise<void>;
}
/** Pure shared presentation. Storage/permissions/editing stay in the host adapter. */
export function CollectionView({ schema, rows, state, onChange, onOpen, renderActions, renderCell, renderCard, columnOptions, writable, onUpdate, }: CollectionViewProps): import("react/jsx-runtime").JSX.Element;

}
declare module "@taskasaur/ui/primitives/dialog" {
import * as React from "react";
import { Dialog as DialogPrimitive } from "@base-ui/react/dialog";
function Dialog({ ...props }: DialogPrimitive.Root.Props): import("react/jsx-runtime").JSX.Element;
function DialogTrigger({ ...props }: DialogPrimitive.Trigger.Props): import("react/jsx-runtime").JSX.Element;
function DialogPortal({ ...props }: DialogPrimitive.Portal.Props): import("react/jsx-runtime").JSX.Element;
function DialogClose({ ...props }: DialogPrimitive.Close.Props): import("react/jsx-runtime").JSX.Element;
function DialogOverlay({ className, ...props }: DialogPrimitive.Backdrop.Props): import("react/jsx-runtime").JSX.Element;
function DialogContent({ className, children, showCloseButton, ...props }: DialogPrimitive.Popup.Props & {
    showCloseButton?: boolean;
}): import("react/jsx-runtime").JSX.Element;
function DialogHeader({ className, ...props }: React.ComponentProps<"div">): import("react/jsx-runtime").JSX.Element;
function DialogFooter({ className, showCloseButton, children, ...props }: React.ComponentProps<"div"> & {
    showCloseButton?: boolean;
}): import("react/jsx-runtime").JSX.Element;
function DialogTitle({ className, ...props }: DialogPrimitive.Title.Props): import("react/jsx-runtime").JSX.Element;
function DialogDescription({ className, ...props }: DialogPrimitive.Description.Props): import("react/jsx-runtime").JSX.Element;
export { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogOverlay, DialogPortal, DialogTitle, DialogTrigger, };

}
declare module "@taskasaur/ui/execution-target" {
import type { AppRuntime } from "@taskasaur/plugin-host";
export interface ExecutionTargetProps {
    runtime: AppRuntime;
    resourceId: string;
    slotId?: string;
    readOnly?: boolean;
}
/** Shared per-item execution controls; only declared execution slots get a picker. */
export function ExecutionTarget({ runtime, resourceId, slotId, readOnly, }: ExecutionTargetProps): import("react/jsx-runtime").JSX.Element | null;

}
declare module "@taskasaur/ui/primitives/alert-dialog" {
import * as React from "react";
import { AlertDialog as AlertDialogPrimitive } from "@base-ui/react/alert-dialog";
import { Button } from "@taskasaur/ui/primitives/button";
function AlertDialog({ ...props }: AlertDialogPrimitive.Root.Props): import("react/jsx-runtime").JSX.Element;
function AlertDialogTrigger({ ...props }: AlertDialogPrimitive.Trigger.Props): import("react/jsx-runtime").JSX.Element;
function AlertDialogPortal({ ...props }: AlertDialogPrimitive.Portal.Props): import("react/jsx-runtime").JSX.Element;
function AlertDialogOverlay({ className, ...props }: AlertDialogPrimitive.Backdrop.Props): import("react/jsx-runtime").JSX.Element;
function AlertDialogContent({ className, size, ...props }: AlertDialogPrimitive.Popup.Props & {
    size?: "default" | "sm";
}): import("react/jsx-runtime").JSX.Element;
function AlertDialogHeader({ className, ...props }: React.ComponentProps<"div">): import("react/jsx-runtime").JSX.Element;
function AlertDialogFooter({ className, ...props }: React.ComponentProps<"div">): import("react/jsx-runtime").JSX.Element;
function AlertDialogMedia({ className, ...props }: React.ComponentProps<"div">): import("react/jsx-runtime").JSX.Element;
function AlertDialogTitle({ className, ...props }: React.ComponentProps<typeof AlertDialogPrimitive.Title>): import("react/jsx-runtime").JSX.Element;
function AlertDialogDescription({ className, ...props }: React.ComponentProps<typeof AlertDialogPrimitive.Description>): import("react/jsx-runtime").JSX.Element;
function AlertDialogAction({ className, ...props }: React.ComponentProps<typeof Button>): import("react/jsx-runtime").JSX.Element;
function AlertDialogCancel({ className, variant, size, ...props }: AlertDialogPrimitive.Close.Props & Pick<React.ComponentProps<typeof Button>, "variant" | "size">): import("react/jsx-runtime").JSX.Element;
export { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogMedia, AlertDialogOverlay, AlertDialogPortal, AlertDialogTitle, AlertDialogTrigger, };

}
declare module "@taskasaur/ui/primitives/calendar" {
import * as React from "react";
import { DayPicker, type DayButton, type Locale } from "react-day-picker";
import { Button } from "@taskasaur/ui/primitives/button";
function Calendar({ className, classNames, showOutsideDays, captionLayout, buttonVariant, locale, formatters, components, ...props }: React.ComponentProps<typeof DayPicker> & {
    buttonVariant?: React.ComponentProps<typeof Button>["variant"];
}): import("react/jsx-runtime").JSX.Element;
function CalendarDayButton({ className, day, modifiers, locale, ...props }: React.ComponentProps<typeof DayButton> & {
    locale?: Partial<Locale>;
}): import("react/jsx-runtime").JSX.Element;
export { Calendar, CalendarDayButton };

}
declare module "@taskasaur/ui/primitives/input-group" {
import * as React from "react";
import { type VariantProps } from "class-variance-authority";
import { Button } from "@taskasaur/ui/primitives/button";
function InputGroup({ className, ...props }: React.ComponentProps<"div">): import("react/jsx-runtime").JSX.Element;
const inputGroupAddonVariants: (props?: ({
    align?: "inline-end" | "inline-start" | "block-start" | "block-end" | null | undefined;
} & import("class-variance-authority/types").ClassProp) | undefined) => string;
function InputGroupAddon({ className, align, ...props }: React.ComponentProps<"div"> & VariantProps<typeof inputGroupAddonVariants>): import("react/jsx-runtime").JSX.Element;
const inputGroupButtonVariants: (props?: ({
    size?: "sm" | "xs" | "icon-xs" | "icon-sm" | null | undefined;
} & import("class-variance-authority/types").ClassProp) | undefined) => string;
function InputGroupButton({ className, type, variant, size, ...props }: Omit<React.ComponentProps<typeof Button>, "size" | "type"> & VariantProps<typeof inputGroupButtonVariants> & {
    type?: "button" | "submit" | "reset";
}): import("react/jsx-runtime").JSX.Element;
function InputGroupText({ className, ...props }: React.ComponentProps<"span">): import("react/jsx-runtime").JSX.Element;
function InputGroupInput({ className, ...props }: React.ComponentProps<"input">): import("react/jsx-runtime").JSX.Element;
function InputGroupTextarea({ className, ...props }: React.ComponentProps<"textarea">): import("react/jsx-runtime").JSX.Element;
export { InputGroup, InputGroupAddon, InputGroupButton, InputGroupText, InputGroupInput, InputGroupTextarea, };

}
declare module "@taskasaur/ui/primitives/command" {
import * as React from "react";
import { Command as CommandPrimitive } from "cmdk";
import { Dialog } from "@taskasaur/ui/primitives/dialog";
function Command({ className, ...props }: React.ComponentProps<typeof CommandPrimitive>): import("react/jsx-runtime").JSX.Element;
function CommandDialog({ title, description, children, className, showCloseButton, ...props }: Omit<React.ComponentProps<typeof Dialog>, "children"> & {
    title?: string;
    description?: string;
    className?: string;
    showCloseButton?: boolean;
    children: React.ReactNode;
}): import("react/jsx-runtime").JSX.Element;
function CommandInput({ className, ...props }: React.ComponentProps<typeof CommandPrimitive.Input>): import("react/jsx-runtime").JSX.Element;
function CommandList({ className, ...props }: React.ComponentProps<typeof CommandPrimitive.List>): import("react/jsx-runtime").JSX.Element;
function CommandEmpty({ className, ...props }: React.ComponentProps<typeof CommandPrimitive.Empty>): import("react/jsx-runtime").JSX.Element;
function CommandGroup({ className, ...props }: React.ComponentProps<typeof CommandPrimitive.Group>): import("react/jsx-runtime").JSX.Element;
function CommandSeparator({ className, ...props }: React.ComponentProps<typeof CommandPrimitive.Separator>): import("react/jsx-runtime").JSX.Element;
function CommandItem({ className, children, ...props }: React.ComponentProps<typeof CommandPrimitive.Item>): import("react/jsx-runtime").JSX.Element;
function CommandShortcut({ className, ...props }: React.ComponentProps<"span">): import("react/jsx-runtime").JSX.Element;
export { Command, CommandDialog, CommandInput, CommandList, CommandEmpty, CommandGroup, CommandItem, CommandShortcut, CommandSeparator, };

}
declare module "@taskasaur/ui/primitives/sheet" {
import * as React from "react";
import { Dialog as SheetPrimitive } from "@base-ui/react/dialog";
function Sheet({ ...props }: SheetPrimitive.Root.Props): import("react/jsx-runtime").JSX.Element;
function SheetTrigger({ ...props }: SheetPrimitive.Trigger.Props): import("react/jsx-runtime").JSX.Element;
function SheetClose({ ...props }: SheetPrimitive.Close.Props): import("react/jsx-runtime").JSX.Element;
function SheetContent({ className, children, side, showCloseButton, ...props }: SheetPrimitive.Popup.Props & {
    side?: "top" | "right" | "bottom" | "left";
    showCloseButton?: boolean;
}): import("react/jsx-runtime").JSX.Element;
function SheetHeader({ className, ...props }: React.ComponentProps<"div">): import("react/jsx-runtime").JSX.Element;
function SheetFooter({ className, ...props }: React.ComponentProps<"div">): import("react/jsx-runtime").JSX.Element;
function SheetTitle({ className, ...props }: SheetPrimitive.Title.Props): import("react/jsx-runtime").JSX.Element;
function SheetDescription({ className, ...props }: SheetPrimitive.Description.Props): import("react/jsx-runtime").JSX.Element;
export { Sheet, SheetTrigger, SheetClose, SheetContent, SheetHeader, SheetFooter, SheetTitle, SheetDescription, };

}
declare module "@taskasaur/ui/primitives/collapsible" {
import { Collapsible as CollapsiblePrimitive } from "@base-ui/react/collapsible";
function Collapsible({ ...props }: CollapsiblePrimitive.Root.Props): import("react/jsx-runtime").JSX.Element;
function CollapsibleTrigger({ ...props }: CollapsiblePrimitive.Trigger.Props): import("react/jsx-runtime").JSX.Element;
function CollapsibleContent({ ...props }: CollapsiblePrimitive.Panel.Props): import("react/jsx-runtime").JSX.Element;
export { Collapsible, CollapsibleTrigger, CollapsibleContent };

}
declare module "@taskasaur/ui/primitives/scroll-area" {
import { ScrollArea as ScrollAreaPrimitive } from "@base-ui/react/scroll-area";
function ScrollArea({ className, children, ...props }: ScrollAreaPrimitive.Root.Props): import("react/jsx-runtime").JSX.Element;
function ScrollBar({ className, orientation, ...props }: ScrollAreaPrimitive.Scrollbar.Props): import("react/jsx-runtime").JSX.Element;
export { ScrollArea, ScrollBar };

}
declare module "@taskasaur/ui/primitives/separator" {
import { Separator as SeparatorPrimitive } from "@base-ui/react/separator";
function Separator({ className, orientation, ...props }: SeparatorPrimitive.Props): import("react/jsx-runtime").JSX.Element;
export { Separator };

}
declare module "@taskasaur/ui/primitives/sonner" {
import { type ToasterProps } from "sonner";
const Toaster: ({ ...props }: ToasterProps) => import("react/jsx-runtime").JSX.Element;
export { Toaster };

}
declare module "@taskasaur/ui/primitives/tabs" {
import { Tabs as TabsPrimitive } from "@base-ui/react/tabs";
import { type VariantProps } from "class-variance-authority";
function Tabs({ className, orientation, ...props }: TabsPrimitive.Root.Props): import("react/jsx-runtime").JSX.Element;
const tabsListVariants: (props?: ({
    variant?: "line" | "default" | null | undefined;
} & import("class-variance-authority/types").ClassProp) | undefined) => string;
function TabsList({ className, variant, ...props }: TabsPrimitive.List.Props & VariantProps<typeof tabsListVariants>): import("react/jsx-runtime").JSX.Element;
function TabsTrigger({ className, ...props }: TabsPrimitive.Tab.Props): import("react/jsx-runtime").JSX.Element;
function TabsContent({ className, ...props }: TabsPrimitive.Panel.Props): import("react/jsx-runtime").JSX.Element;
export { Tabs, TabsList, TabsTrigger, TabsContent, tabsListVariants };

}
declare module "@taskasaur/ui/primitives/toggle" {
import { Toggle as TogglePrimitive } from "@base-ui/react/toggle";
import { type VariantProps } from "class-variance-authority";
const toggleVariants: (props?: ({
    variant?: "default" | "outline" | null | undefined;
    size?: "sm" | "default" | "lg" | null | undefined;
} & import("class-variance-authority/types").ClassProp) | undefined) => string;
function Toggle({ className, variant, size, ...props }: TogglePrimitive.Props & VariantProps<typeof toggleVariants>): import("react/jsx-runtime").JSX.Element;
export { Toggle, toggleVariants };

}
declare module "@taskasaur/ui/primitives/combobox" {
import * as React from "react";
import { Combobox as ComboboxPrimitive } from "@base-ui/react";
const Combobox: typeof ComboboxPrimitive.Root;
function ComboboxValue({ ...props }: ComboboxPrimitive.Value.Props): import("react/jsx-runtime").JSX.Element;
function ComboboxTrigger({ className, children, ...props }: ComboboxPrimitive.Trigger.Props): import("react/jsx-runtime").JSX.Element;
function ComboboxInput({ className, children, disabled, showTrigger, showClear, ...props }: ComboboxPrimitive.Input.Props & {
    showTrigger?: boolean;
    showClear?: boolean;
}): import("react/jsx-runtime").JSX.Element;
function ComboboxContent({ className, side, sideOffset, align, alignOffset, anchor, ...props }: ComboboxPrimitive.Popup.Props & Pick<ComboboxPrimitive.Positioner.Props, "side" | "align" | "sideOffset" | "alignOffset" | "anchor">): import("react/jsx-runtime").JSX.Element;
function ComboboxList({ className, ...props }: ComboboxPrimitive.List.Props): import("react/jsx-runtime").JSX.Element;
function ComboboxItem({ className, children, ...props }: ComboboxPrimitive.Item.Props): import("react/jsx-runtime").JSX.Element;
function ComboboxGroup({ className, ...props }: ComboboxPrimitive.Group.Props): import("react/jsx-runtime").JSX.Element;
function ComboboxLabel({ className, ...props }: ComboboxPrimitive.GroupLabel.Props): import("react/jsx-runtime").JSX.Element;
function ComboboxCollection({ ...props }: ComboboxPrimitive.Collection.Props): import("react/jsx-runtime").JSX.Element;
function ComboboxEmpty({ className, ...props }: ComboboxPrimitive.Empty.Props): import("react/jsx-runtime").JSX.Element;
function ComboboxSeparator({ className, ...props }: ComboboxPrimitive.Separator.Props): import("react/jsx-runtime").JSX.Element;
function ComboboxChips({ className, ...props }: React.ComponentPropsWithRef<typeof ComboboxPrimitive.Chips> & ComboboxPrimitive.Chips.Props): import("react/jsx-runtime").JSX.Element;
function ComboboxChip({ className, children, showRemove, ...props }: ComboboxPrimitive.Chip.Props & {
    showRemove?: boolean;
}): import("react/jsx-runtime").JSX.Element;
function ComboboxChipsInput({ className, ...props }: ComboboxPrimitive.Input.Props): import("react/jsx-runtime").JSX.Element;
function useComboboxAnchor(): React.RefObject<HTMLDivElement | null>;
export { Combobox, ComboboxInput, ComboboxContent, ComboboxList, ComboboxItem, ComboboxGroup, ComboboxLabel, ComboboxCollection, ComboboxEmpty, ComboboxSeparator, ComboboxChips, ComboboxChip, ComboboxChipsInput, ComboboxTrigger, ComboboxValue, useComboboxAnchor, };

}
declare module "@taskasaur/ui/primitives/badge" {
import { useRender } from "@base-ui/react/use-render";
import { type VariantProps } from "class-variance-authority";
const badgeVariants: (props?: ({
    variant?: "link" | "default" | "outline" | "secondary" | "ghost" | "destructive" | null | undefined;
} & import("class-variance-authority/types").ClassProp) | undefined) => string;
function Badge({ className, variant, render, ...props }: useRender.ComponentProps<"span"> & VariantProps<typeof badgeVariants>): import("react").ReactElement<unknown, string | import("react").JSXElementConstructor<any>>;
export { Badge, badgeVariants };

}
declare module "@taskasaur/ui/download" {
export function download(name: string, blob: Blob): void;

}
declare module "@taskasaur/ui/record-table" {
import { type ReactNode } from "react";
import { type Value, type RecordSchema } from "@taskasaur/platform/field-types";
import type { ResourceRecord } from "@taskasaur/platform/plugin-sdk";
import type { AppRuntime } from "@taskasaur/plugin-host";
import { type CellContext, type ColumnOptions } from "@taskasaur/ui/collection-view";
import { type CollectionViewState } from "@taskasaur/ui/collection-view-model";
export interface RecordTableProps {
    runtime: AppRuntime;
    collection: string;
    toolbar?: ReactNode;
    renderActions?: (row: ResourceRecord, context: {
        writable: boolean;
        update: (patch: Record<string, Value>) => Promise<void>;
    }) => ReactNode;
    onOpen?: (row: ResourceRecord) => void;
    hideCreate?: boolean;
    schemaOverride?: RecordSchema;
    storeOverride?: {
        list: () => Promise<ResourceRecord[]>;
        put: (data: any, id?: string) => Promise<ResourceRecord>;
        delete: (id: string) => Promise<unknown>;
    };
    viewKey?: string;
    readOnly?: boolean;
    /** Host supplies the owning plugin when editing managed shared resources. */
    managedAccess?: string;
    defaultView?: Partial<CollectionViewState>;
    renderCell?: (context: CellContext) => ReactNode;
    renderCard?: (row: ResourceRecord, defaultContent: ReactNode) => ReactNode;
    columnOptions?: Record<string, ColumnOptions>;
}
/** Storage/permissions adapter. Every plugin gets the same collection presentation. */
export function RecordTable({ runtime, collection, toolbar, renderActions, onOpen, hideCreate, schemaOverride, storeOverride, viewKey, readOnly, managedAccess, defaultView, renderCell, renderCard, columnOptions, }: RecordTableProps): import("react/jsx-runtime").JSX.Element;

}